### ISSUE TITLE
error in attribute with construct module

### ISSUE THREAD

**Issue by huyusukesan** [volatilityfoundation/community#15]
when i import mimikatz module in python i receive this error:

  File "mimikatz.py", line 183, in LsaDecryptor
    construct.ULInt32('cbSecret'),
AttributeError: 'module' object has no attribute 'ULInt32'

import module construct is OK.
but in construct module the definition of UnsignedLong 32 is:   "Int32ul"  and not "ULInt32"    !!!

please could you correct this mistake in definition of object ? i think the other ULInt*\* as the same error .

thanks

Ps: python version is 2.7.6

**Comment by kevthehermit** [comment]
You can try 
`sudo pip uninstall construct`

`sudo pip install construct==2.5.5-reupload`

This is the last stable release that has the old names.

**Comment by huyusukesan** [comment]
ok thank's
that's allright now.

**Comment by gleeda** [comment]
Since this is resolved, I'm going to close it out.

**Comment by Github3362** [comment]
Why can't I
![image](https://github.com/user-attachments/assets/89a0921c-14a0-4d4a-8664-de288c801e37)
