### ISSUE TITLE
Import error in DimaPshoul/malthfind.py

### ISSUE THREAD

**Issue by morallo** [volatilityfoundation/community#17]
I couldn't find any "upstream" repo, so I create the issue here.

When trying to import this plugin, it gives an error:
> *** Failed to import volatility.plugins.community.DimaPshoul.malthfind (ImportError: No module named callstacks)

Checking the code, it seems it tries to import a non existing module:

`import volatility.plugins.malware.callstacks as callstacks`

I think @papadp wants to import his own callstacks module (`callstacks.py` in the same directory).

**Comment by gleeda** [comment]
merged
